
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AccesoDatosEF
{

using System;
    using System.Collections.Generic;
    
public partial class CustomerCustomerDemo
{

    public string CustomerID { get; set; }

    public string CustomerTypeID { get; set; }

}

}
