

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AccesoDatosEF
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class NorthwindEntities : DbContext
{
    public NorthwindEntities()
        : base("name=NorthwindEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Employees> Employees { get; set; }

    public virtual DbSet<Order_Details> Order_Details { get; set; }

    public virtual DbSet<CustomerCustomerDemo> CustomerCustomerDemo { get; set; }


    public virtual ObjectResult<GetAllEmployees_Result> GetAllEmployees()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllEmployees_Result>("GetAllEmployees");
    }


    public virtual ObjectResult<GetEmployeebyName_Result> GetEmployeebyName(string firstname)
    {

        var firstnameParameter = firstname != null ?
            new ObjectParameter("firstname", firstname) :
            new ObjectParameter("firstname", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployeebyName_Result>("GetEmployeebyName", firstnameParameter);
    }


    public virtual ObjectResult<GetEmployeesAsc_Result> GetEmployeesAsc()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployeesAsc_Result>("GetEmployeesAsc");
    }

}

}

